### ISSUE TITLE
BUG: brew configuration

### ISSUE THREAD

**Issue by sgaunet** [sgaunet/jwt-cli#7]
Brew configuration in goreleaser file omit the directory of the Formula

**Comment by sgaunet** [comment]
Add/fix documentation:

```
brew tap sgaunet/homebrew-tools
brew install sgaunet/tools/jwt-cli
```

Fix goreleaser configuration:

```
brews:
  - homepage: 'https://github.com/sgaunet/homebrew-tools'
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
```
